"use strict";

const ON = true;
const OFF = null;

module.exports = {
  rules: {
    // Possible errors
    "at-rule-no-unknown": ON,
    "block-no-empty": ON,
    "color-no-invalid-hex": ON,
    "comment-no-empty": ON,
    "declaration-block-no-duplicate-properties": [
      ON,
      {
        ignore: ["consecutive-duplicates"]
      }
    ],
    "declaration-block-no-shorthand-property-overrides": ON,
    "font-family-no-duplicate-names": ON,
    "font-family-no-missing-generic-family-keyword": ON,
    "function-calc-no-unspaced-operator": ON,
    "function-linear-gradient-no-nonstandard-direction": ON,
    "keyframe-declaration-no-important": ON,
    "media-feature-name-no-unknown": ON,
    "no-descending-specificity": OFF,
    "no-duplicate-at-import-rules": ON,
    "no-duplicate-selectors": ON,

    "no-empty-source": OFF,
    "no-extra-semicolons": ON,
    "no-invalid-double-slash-comments": ON,
    "property-no-unknown": ON,
    "selector-pseudo-class-no-unknown": ON,
    "selector-pseudo-element-no-unknown": ON,
    "selector-type-no-unknown": ON,
    "string-no-newline": ON,
    "unit-no-unknown": ON,

    // Limit language features
    "at-rule-blacklist": ["extend"],
    "at-rule-no-vendor-prefix": OFF,
    "at-rule-whitelist": OFF,
    "color-named": "never",
    "color-no-hex": OFF,
    "comment-word-blacklist": OFF,
    "custom-media-pattern": OFF,
    "custom-property-pattern": OFF,
    "declaration-block-no-redundant-longhand-properties": OFF,
    "declaration-block-single-line-max-declarations": 1,
    "declaration-no-important": OFF,
    "declaration-property-unit-blacklist": OFF,
    "declaration-property-unit-whitelist": OFF,
    "declaration-property-value-blacklist": {
      "/^transition/": ["/all/"],
      "/^background/": ["http:", "https:"],
      "/^border/": ["none"],
      "/.+/": ["initial"]
    },
    "declaration-property-value-blacklist": OFF,
    "declaration-property-value-whitelist": OFF,
    "function-blacklist": OFF,
    "function-url-no-scheme-relative": OFF,
    "function-url-scheme-blacklist": OFF,
    "function-url-scheme-whitelist": OFF,
    "function-whitelist": OFF,
    "max-nesting-depth": 6,
    "media-feature-name-blacklist": OFF,
    "media-feature-name-no-vendor-prefix": OFF,
    "media-feature-name-whitelist": OFF,
    "no-unknown-animations": OFF,
    "number-max-precision": OFF,
    "property-blacklist": OFF,
    "property-no-vendor-prefix": ON,
    "property-whitelist": OFF,
    "selector-attribute-operator-blacklist": OFF,
    "selector-attribute-operator-whitelist": OFF,
    "selector-class-pattern": OFF,
    "selector-combinator-blacklist": OFF,
    "selector-combinator-whitelist": OFF,
    "selector-id-pattern": OFF,
    "selector-max-attribute": OFF,
    "selector-max-class": OFF,
    "selector-max-combinators": OFF,
    "selector-max-compound-selectors": 5,
    "selector-max-empty-lines": 0,
    "selector-max-id": 0,
    "selector-max-pseudo-class": OFF,
    "selector-max-specificity": "0,5,0",
    "selector-max-type": 1,
    "selector-max-universal": OFF,
    "selector-nested-pattern": OFF,
    "selector-no-qualifying-type": OFF,
    "selector-no-vendor-prefix": OFF,
    "selector-pseudo-class-blacklist": OFF,
    "selector-pseudo-class-whitelist": OFF,
    "selector-pseudo-element-blacklist": OFF,
    "selector-pseudo-element-whitelist": OFF,
    "shorthand-property-no-redundant-values": ON,
    "time-min-milliseconds": OFF,
    "unit-blacklist": OFF,
    "unit-whitelist": OFF,
    "value-no-vendor-prefix": ON,

    // Stylistic issues
    "at-rule-empty-line-before": OFF,
    "at-rule-name-case": "lower",
    "at-rule-name-newline-after": OFF,
    "at-rule-name-space-after": "always-single-line",
    "at-rule-semicolon-newline-after": "always",
    "at-rule-semicolon-space-before": OFF,
    "block-closing-brace-empty-line-before": OFF,
    "block-closing-brace-newline-after": OFF,
    "block-closing-brace-newline-before": "always-multi-line",
    "block-closing-brace-space-after": OFF,
    "block-closing-brace-space-before": "always-single-line",
    "block-opening-brace-newline-after": "always-multi-line",
    "block-opening-brace-newline-before": OFF,
    "block-opening-brace-space-after": "always-single-line",
    "block-opening-brace-space-before": "always",
    "color-hex-case": "lower",
    "color-hex-length": "short",
    "comment-empty-line-before": [
      "always",
      {
        except: ["first-nested"],
        ignore: ["stylelint-commands"]
      }
    ],
    "comment-whitespace-inside": "always",
    "custom-property-empty-line-before": OFF,
    "declaration-bang-space-after": "never",
    "declaration-bang-space-before": "always",
    "declaration-block-semicolon-newline-after": "always",
    "declaration-block-semicolon-newline-before": OFF,
    "declaration-block-semicolon-space-after": OFF,
    "declaration-block-semicolon-space-before": "never",
    "declaration-block-trailing-semicolon": "always",
    "declaration-colon-newline-after": OFF,
    "declaration-colon-space-after": "always-single-line",
    "declaration-colon-space-before": "never",
    "declaration-empty-line-before": OFF,
    "font-family-name-quotes": "always-where-recommended",
    "font-weight-notation": OFF,
    "function-comma-newline-after": "always-multi-line",
    "function-comma-newline-before": OFF,
    "function-comma-space-after": "always-single-line",
    "function-comma-space-before": "never",
    "function-max-empty-lines": 0,
    "function-name-case": "lower",
    "function-parentheses-newline-inside": "always-multi-line",
    "function-parentheses-space-inside": "never-single-line",
    "function-url-quotes": "always",
    "function-whitespace-after": "always",
    indentation: 2,
    "length-zero-no-unit": ON,
    "max-empty-lines": 1,
    "max-line-length": OFF,
    "media-feature-colon-space-after": "always",
    "media-feature-colon-space-before": "never",
    "media-feature-name-case": OFF,
    "media-feature-parentheses-space-inside": "never",
    "media-feature-range-operator-space-after": "always",
    "media-feature-range-operator-space-before": "always",
    "media-query-list-comma-newline-after": "always-multi-line",
    "media-query-list-comma-newline-before": OFF,
    "media-query-list-comma-space-after": "always-single-line",
    "media-query-list-comma-space-before": "never",
    "no-eol-whitespace": ON,
    "no-missing-end-of-source-newline": ON,
    "number-leading-zero": "always",
    "number-no-trailing-zeros": ON,
    "property-case": "lower",
    "rule-empty-line-before": [
      "always-multi-line",
      {
        except: ["first-nested"],
        ignore: ["after-comment"]
      }
    ],
    "selector-attribute-brackets-space-inside": "never",
    "selector-attribute-operator-space-after": "never",
    "selector-attribute-operator-space-before": "never",
    "selector-attribute-quotes": OFF,
    "selector-combinator-space-after": "always",
    "selector-combinator-space-before": "always",
    "selector-descendant-combinator-no-non-space": OFF,
    "selector-list-comma-newline-after": "always",
    "selector-list-comma-newline-before": OFF,
    "selector-list-comma-space-after": "always-single-line",
    "selector-list-comma-space-before": "never",
    "selector-pseudo-class-case": "lower",
    "selector-pseudo-class-parentheses-space-inside": "never",
    "selector-pseudo-element-case": "lower",
    "selector-pseudo-element-colon-notation": "double",
    "selector-type-case": "lower",
    "string-quotes": "double",
    "unit-case": "lower",
    "value-keyword-case": OFF,
    "value-list-comma-newline-after": "always-multi-line",
    "value-list-comma-newline-before": OFF,
    "value-list-comma-space-after": "always-single-line",
    "value-list-comma-space-before": "never",
    "value-list-max-empty-lines": OFF
  }
};
